## Lab 5: Least Squares Regression Models

The purpose of this lab is to utilize the computing power of the scikit-learn environment to build linear models that predict numeric variable values. 



#### Selecting Columns by Slicing.
A note about selecting columns for building a design matrix X: 

Suppose you have a dataset in a pandas data frame ``df`` with 500 observations and 12 variables. If you wanted to predict the 2nd variable from the other 11 you could do ```X = df.to_numpy()[:,[0,2,3,4,5,6,7,8,9,10,11]]``` and ```y = df.to_numpy()[:,1]```. 

### I. Least Squares Regression Models

The following exercises will utilize the ```swiss``` data set. Read about the data set here: https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/swiss.

In [ ]:
# Step 1: Import babies dataset
from google.colab import files

uploaded = files.upload()


Saving swiss.csv to swiss.csv


In [ ]:
# Step 2: View dataset

import pandas as pd

swisses = pd.read_csv("swiss.csv")
swisses.head()

Providence  Fertility  Agriculture  Examination  Education  Catholic  \
0    Courtelary       80.2         17.0           15         12      9.96   
1      Delemont       83.1         45.1            6          9     84.84   
2  Franches-Mnt       92.5         39.7            5          5     93.40   
3       Moutier       85.8         36.5           12          7     33.77   
4    Neuveville       76.9         43.5           17         15      5.16   

   Infant_Mortality  
0              22.2  
1              22.2  
2              20.2  
3              20.3  
4              20.6

**Exercise 1**. How many providences are in the data set? 

In [ ]:
x = len(swisses)
print(x)
#47

47


**Exercise 2**. Not including ```Providence```, how many variables are in the data set? 

 

In [ ]:
#6

**Exercise 3**. We want to predict ```Education``` from the other variables (not including ```Providence```). Fit the following regression model to the data:

\begin{align} \hat{Education} = \hat{\beta_0} + \hat{\beta_1}Fertility + \hat{\beta_2}Agriculture + \hat{\beta_3}Examination + \hat{\beta_4}Catholic + \hat{\beta_5}Infant\_Mortality.\end{align}

$\hat{\beta_4}$ = ____. 



In [ ]:
import numpy as np

X = swisses.to_numpy()[:,[1,2,3,5,6]]# Note that we don't need to do a column of ones since sklearn will do it for us.
y = swisses.to_numpy()[:,4]
print(X)
print()
print(y)

[[80.2 17.0 15 9.96 22.2]
 [83.1 45.1 6 84.84 22.2]
 [92.5 39.7 5 93.4 20.2]
 [85.8 36.5 12 33.77 20.3]
 [76.9 43.5 17 5.16 20.6]
 [76.1 35.3 9 90.57 26.6]
 [83.8 70.2 16 92.85 23.6]
 [92.4 67.8 14 97.16 24.9]
 [82.4 53.3 12 97.67 21.0]
 [82.9 45.2 16 91.38 24.4]
 [87.1 64.5 14 98.61 24.5]
 [64.1 62.0 21 8.52 16.5]
 [66.9 67.5 14 2.27 19.1]
 [68.9 60.7 19 4.43 22.7]
 [61.7 69.3 22 2.82 18.7]
 [68.3 72.6 18 24.2 21.2]
 [71.7 34.0 17 3.3 20.0]
 [55.7 19.4 26 12.11 20.2]
 [54.3 15.2 31 2.15 10.8]
 [65.1 73.0 19 2.84 20.0]
 [65.5 59.8 22 5.23 18.0]
 [65.0 55.1 14 4.52 22.4]
 [56.6 50.9 22 15.14 16.7]
 [57.4 54.1 20 4.2 15.3]
 [72.5 71.2 12 2.4 21.0]
 [74.2 58.1 14 5.23 23.8]
 [72.0 63.5 6 2.56 18.0]
 [60.5 60.8 16 7.72 16.3]
 [58.3 26.8 25 18.46 20.9]
 [65.4 49.5 15 6.1 22.5]
 [75.5 85.9 3 99.71 15.1]
 [69.3 84.9 7 99.68 19.8]
 [77.3 89.7 5 100.0 18.3]
 [70.5 78.2 12 98.96 19.4]
 [79.4 64.9 7 98.22 20.2]
 [65.0 75.9 9 99.06 17.8]
 [92.2 84.6 3 99.46 16.3]
 [79.3 63.1 13 96.83 18.1]
 [70.4 

In [ ]:
from sklearn.linear_model import LinearRegression

swiss_model = LinearRegression().fit(X, y)

print(swiss_model.coef_)
print()
print(swiss_model.intercept_)

#Q3 0.1002

[-0.40850563 -0.16241527  0.41980309  0.10023066  0.2040833 ]

32.74413967505881


**Exercise 4**. The model from the previous exercise predicts that a providence with ```Fertility``` = 80.2, ```Agriculture``` = 17, ```Examination``` = 15, ```Catholic``` = 9.96, and ```Infant_Mortality``` = 22.2 will have a post-primary military draftee education level of ___%.

In [ ]:
swiss_in = np.array([[80.2,17,15,9.96,22.2]])

print(swiss_model.predict(swiss_in))
#9.0469


[9.04692135]


**Exercise 5**. This model explains ____% of the variation in the ```Education``` variable.

In [ ]:
#R2
r2 = swiss_model.score(X, y)
print("R^2:", r2)
#0.7678


R^2: 0.767845274769381


**Exercise 6**. Find the Residual Squared Error (RSE) for our model. (Hint: Find SSE by first finding MSE.) 

In [ ]:
import math
y_hat = swiss_model.predict(X)
print("y_hat", y_hat)
sse = np.sum((y-y_hat)**2)
print("sse", sse)
n = X.shape[0]
mse = sse / n
print("MSE", mse)
p = X.shape[1]
rse = math.sqrt(sse / (n - p - 1))
print("RSE", rse)
#4.9073

y_hat [ 9.04692135  7.02542969  4.09252391  4.33151648  6.12295113 14.20833617
  7.94944762  4.68379206  9.53945633 12.39341193  7.44854342  9.52638662
  4.45484024  7.79246633  9.6186403   7.36046005  9.48124645 23.090676
 23.52706312  6.6366883   9.7079615   8.14394411 15.51713501 12.44875548
  1.12745428  4.25532687 -0.53272688  8.97188858 21.18620827  9.4886432
  2.28555876  7.6161059   2.45481024 10.15929748  6.67380091 11.20371409
 -4.10550315  8.95792195 13.36966452 22.39490006 14.55087554 24.66079498
  5.81414727 17.4336902  41.70152389 22.40118392 29.78212551]
sse 987.3491069435836
MSE 21.00742780731029
RSE 4.907309398765209


**Exercise 7**. Consider every possible least squares regression model to predict ```Education``` that uses only a single variable as its input. The model that performs the best, as measured by MSE, is \begin{align}\hat{Education} = \hat{\beta_0} + \hat{\beta_1}x, \end{align} where x = "_______".

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X = swisses.to_numpy()[:,[1]]
X1 = swisses.to_numpy()[:,[2]]
#X = fertility.reshape(-1, 1)
#X1 = agriculture.reshape(-1,1)
y = swisses['Education'].to_numpy()

fertility_model = LinearRegression().fit(X, y)
print(fertility_model.coef_)

print(fertility_model.intercept_)
print()
agriculture_model = LinearRegression().fit(X1, y)
print(agriculture_model.coef_)
print(agriculture_model.intercept_)


y_pred = fertility_model.predict(X)
mse = mean_squared_error(y, y_pred)


y1_pred = agriculture_model.predict(X1)
mse1 = mean_squared_error(y, y1_pred)

print("mse", mse)
print("mse1", mse1)


[-0.51094741]
46.81787913987708

[-0.27075913]
24.695265624790103
mse 50.618079844434114
mse1 53.4799358747604


**Exercise 8**. Use what you know about column spaces and the least-squares solution to explain (in several full sentences) why the model in Exercise 3 outperforms those in Exercise 7. What is happening with the error vector graphically? 

using multiple independent variables in a multiple linear regression model allows for more accurate prediction

**Exercise 9**. Suppose you accidentally fit a model of the form 

\begin{align}\hat{Education} = \hat{\beta_0} + \hat{\beta_1}Fertility + \hat{\beta_2}Agriculture + \hat{\beta_3}Education.\end{align}

What will the SSE be for this model? Explain why this makes sense because of where the ```Education``` vector is located relative to the column space of the design matrix. 

In [ ]:
SSE will be 0 because the linear combination perfectly predicts the education variable. It includes education. The column space of the design matrix contains the education vector, which could represent exactly the linear combination of the education vector in that design matrix. 

**Exercise 10**. Is the ```Agriculture``` variable useful for predicting ```Infant_Mortality```? What is $\hat{\beta_{Agriculture}}$ for this simple model? What does this tell you about the relationship between these two variables? 



In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X = swisses.to_numpy()[:,[2]]
print(X)
print()
y = swisses.to_numpy()[:,6]
print(y)

By applying the code we can see that the coefficient is -0.00780507, which means that a increase the Agriculture will decrease the Infat_Mortality. 

[[17.0]
 [45.1]
 [39.7]
 [36.5]
 [43.5]
 [35.3]
 [70.2]
 [67.8]
 [53.3]
 [45.2]
 [64.5]
 [62.0]
 [67.5]
 [60.7]
 [69.3]
 [72.6]
 [34.0]
 [19.4]
 [15.2]
 [73.0]
 [59.8]
 [55.1]
 [50.9]
 [54.1]
 [71.2]
 [58.1]
 [63.5]
 [60.8]
 [26.8]
 [49.5]
 [85.9]
 [84.9]
 [89.7]
 [78.2]
 [64.9]
 [75.9]
 [84.6]
 [63.1]
 [38.4]
 [7.7]
 [16.7]
 [17.6]
 [37.6]
 [18.7]
 [1.2]
 [46.6]
 [27.7]]

[22.2 22.2 20.2 20.3 20.6 26.6 23.6 24.9 21.0 24.4 24.5 16.5 19.1 22.7
 18.7 21.2 20.0 20.2 10.8 20.0 18.0 22.4 16.7 15.3 21.0 23.8 18.0 16.3
 20.9 22.5 15.1 19.8 18.3 19.4 20.2 17.8 16.3 18.1 20.3 20.5 18.9 23.0
 20.0 19.5 18.0 18.2 19.3]


In [ ]:
from sklearn.linear_model import LinearRegression

swiss_model = LinearRegression().fit(X, y)

print(swiss_model.coef_)
print()
print(swiss_model.intercept_)


[-0.00780507]

20.337954766136615
